require("haoliu.plugins-setup")
require("haoliu.core.options")
require("haoliu.core.keymaps")
require("haoliu.core.colorscheme")
require("haoliu.plugins.comment")
-- require("haoliu.plugins.nvim-tree")
require("haoliu.plugins.lualine")
require("haoliu.plugins.telescope")
require("haoliu.plugins.nvim-cmp")
require("haoliu.plugins.lsp.mason")
require("haoliu.plugins.lsp.lspsaga")
require("haoliu.plugins.lsp.lspconfig")
require("haoliu.plugins.lsp.null-ls")
require("haoliu.plugins.autopairs")
require("haoliu.plugins.treesitter")
require("haoliu.plugins.gitsigns")
require("haoliu.plugins.toggleterm")

require("haoliu.plugins.whichkey")
require("haoliu.plugins.harpoon")
